services:
  db:
    image: postgres:13
    container_name: local_pgdb
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=german
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data